# Generated by Django 4.2.6 on 2023-10-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('dataIni', models.DateTimeField()),
                ('dataFi', models.DateTimeField()),
                ('nom', models.CharField(max_length=255)),
                ('descripcio', models.TextField()),
                ('preu', models.DecimalField(decimal_places=2, max_digits=10)),
                ('horaris', models.TextField()),
                ('enllac', models.URLField()),
                ('adreca', models.CharField(max_length=255)),
                ('imatge', models.ImageField(upload_to='~/images/')),
            ],
        ),
    ]
