# Generated by Django 4.2.6 on 2023-11-20 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('dataIni', models.DateTimeField(blank=True, null=True)),
                ('dataFi', models.DateTimeField(blank=True, null=True)),
                ('nom', models.CharField()),
                ('descripcio', models.TextField(blank=True, null=True)),
                ('preu', models.CharField(blank=True, null=True)),
                ('horaris', models.TextField(blank=True, null=True)),
                ('enllac', models.CharField(blank=True, null=True)),
                ('adreca', models.CharField(blank=True, null=True)),
                ('imatge', models.CharField(blank=True, null=True)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('isAdminCreated', models.BooleanField(blank=True, default=False)),
                ('espai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spaces.space')),
                ('tags', models.ManyToManyField(to='tags.tag')),
            ],
        ),
    ]
