# Generated by Django 4.2.6 on 2023-12-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='municipi',
            field=models.CharField(blank=True, null=True),
        ),
    ]
