# Generated by Django 4.2.6 on 2023-12-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='images/eventDefault.jpg', upload_to='images/'),
        ),
    ]
