# Generated by Django 4.2.6 on 2023-10-20 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='espai',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='spaces.space'),
        ),
        migrations.AddField(
            model_name='event',
            name='latitud',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='event',
            name='longitud',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='event',
            name='imatge',
            field=models.CharField(),
        ),
    ]
