# Generated by Django 4.2.6 on 2024-01-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='adreca',
            field=models.CharField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='descripcio',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='enllac',
            field=models.CharField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='horaris',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='imatge',
            field=models.CharField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='municipi',
            field=models.CharField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
