# Generated by Django 4.2.6 on 2023-10-20 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0001_initial'),
        ('events', '0002_event_espai_event_latitud_event_longitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='dataFi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='dataIni',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='descripcio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='enllac',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='espai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spaces.space'),
        ),
        migrations.AlterField(
            model_name='event',
            name='horaris',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='imatge',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='nom',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='preu',
            field=models.CharField(blank=True, null=True),
        ),
    ]
