# Generated by Django 4.2.6 on 2024-01-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_adreca_alter_event_descripcio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='preu',
            field=models.CharField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
