# Generated by Django 4.2.6 on 2023-11-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('events', '0005_event_isadmincreated'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(to='tags.tag'),
        ),
    ]
