# Generated by Django 4.2.6 on 2023-11-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('codi', models.CharField(primary_key=True, serialize=False)),
                ('nivellTrofeu', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')])),
                ('nomTrofeu', models.CharField()),
                ('usat', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['nomTrofeu', 'nivellTrofeu'],
            },
        ),
    ]
