# Generated by Django 4.2.6 on 2023-11-16 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('codi', models.CharField(primary_key=True, serialize=False)),
                ('nivellTrofeu', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')])),
                ('nomTrofeu', models.CharField()),
                ('usat', models.BooleanField(default=False)),
                ('userDiscount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nomTrofeu', 'nivellTrofeu'],
            },
        ),
    ]
