<<<<<<< Updated upstream
# Generated by Django 4.2.6 on 2023-11-20 19:44
=======
# Generated by Django 4.2.6 on 2023-11-11 16:20
>>>>>>> Stashed changes

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
<<<<<<< Updated upstream
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(null=True, unique=True)),
=======
                ('nom', models.CharField(primary_key=True, serialize=False)),
>>>>>>> Stashed changes
            ],
        ),
    ]
