# Generated by Django 4.2.6 on 2023-10-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='isAdmin',
            field=models.BooleanField(default=False, verbose_name="L'usuari es administrador"),
        ),
        migrations.DeleteModel(
            name='Administrador',
        ),

    ]
