# Generated by Django 4.2.6 on 2023-11-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='tags_preferits',
            field=models.ManyToManyField(blank=True, related_name='perfils', to='tags.tag', verbose_name='Tags preferits'),
        ),
    ]
