# Generated by Django 4.2.6 on 2023-11-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='wantsNotifications',
            field=models.BooleanField(default=True, verbose_name='Permet notificacions'),
        ),
    ]
