# Generated by Django 4.2.6 on 2023-10-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_perfil_isadmin_perfil_isblocked_perfil_isvisible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='isBlocked',
            field=models.BooleanField(default=False, verbose_name='Està bloquejat a la aplicacio'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='isVisible',
            field=models.BooleanField(default=True, verbose_name='La resta dels usuaris el poden trobar'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='puntuacio',
            field=models.IntegerField(default=0, verbose_name='Puntuacio'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='wantsToTalk',
            field=models.BooleanField(default=True, verbose_name='La resta dels usuaris poden parlar amb ell'),
        ),
    ]
