# Generated by Django 4.2.6 on 2023-10-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0001_initial'),
        ('user', '0002_perfil_isadmin_perfil_isblocked_perfil_isvisible_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trofeu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('descripcio', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='perfil',
            name='llocs_favorits',
            field=models.ManyToManyField(blank=True, to='spaces.space', verbose_name='Llocs Favorits'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='trofeus',
            field=models.ManyToManyField(blank=True, to='user.trofeu', verbose_name='Trofeus'),
        ),
    ]
