# Generated by Django 4.2.6 on 2023-12-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_perfil_imatge'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='isGoogleUser',
            field=models.BooleanField(default=False, verbose_name="L'usuari és de Google"),
        ),
        migrations.AddField(
            model_name='perfil',
            name='usernameGoogle',
            field=models.CharField(max_length=150, null=True, verbose_name='Username pels usuaris de Google'),
        ),
    ]
