# Generated by Django 4.2.6 on 2023-12-06 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('spaces', '0001_initial'),
        ('user', '0003_perfil_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='espais_preferits',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='tags_preferits',
        ),
        migrations.CreateModel(
            name='TagPreferit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='Comptador de vegades')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.tag', verbose_name='Tag preferit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.perfil', verbose_name='User amb tag preferit')),
            ],
        ),
        migrations.CreateModel(
            name='SpacePreferit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='Comptador de vegades')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaces.space', verbose_name='Espai preferit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.perfil', verbose_name='User amb tag preferit')),
            ],
        ),
    ]
