# Generated by Django 4.2.6 on 2023-12-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_perfil_isgoogleuser_perfil_usernamegoogle'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='imatge_url',
            field=models.CharField(null=True, verbose_name='Imatge si es fa log in de Google'),
        ),
    ]
