# Generated by Django 4.2.6 on 2023-12-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_spacepreferit_show_tagpreferit_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imatge',
            field=models.ImageField(default='https://www.calfruitos.com/es/fotos/pr_223_20190304145434.png', upload_to='images/'),
        ),
    ]
