# Generated by Django 4.2.6 on 2023-10-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.TextField(max_length=560)),
                ('event', models.TextField(max_length=560)),
                ('text', models.TextField(max_length=560)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
