# Generated by Django 4.2.6 on 2023-10-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(max_length=560)),
                ('event', models.TextField(max_length=560)),
                ('image', models.ImageField(default='images/qr.png', upload_to='tickets/')),
            ],
            options={
                'unique_together': {('user', 'event')},
            },
        ),
    ]
