# Generated by Django 4.2.6 on 2023-11-29 17:23

from django.db import migrations, models
import ticket.models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.CharField(default=ticket.models.get_random_image, max_length=200),
        ),
    ]
