# Generated by Django 4.2.6 on 2024-01-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_alter_ticket_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='pdf_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
