# Generated by Django 4.2.6 on 2024-01-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_ticket_pdf_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='pdf_url',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
