# Generated by Django 4.2.6 on 2023-11-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trophy',
            fields=[
                ('nom', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('descripcio', models.TextField(max_length=300)),
                ('punts_nivell1', models.IntegerField()),
                ('punts_nivell2', models.IntegerField()),
                ('punts_nivell3', models.IntegerField()),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
    ]
