name: Deploy to Google Cloud

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
        - name: Debug Message
          run: echo "Workflow is running."

        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
                python-version: 3.10.6

        - name: Install dependencies
          run: |
            echo "Installing dependencies..."
            python -m pip install --upgrade pip
            pip install -r requirements.txt


        - name: Deploy to Google Cloud
          run: |
            gcloud config set project "cultucat-405114"
            gcloud compute ssh "cultucat-back" --zone "us-central1-a" --command "sudo -i -u emanuel.cuevas03 && cd backend/ && git pull origin master && sudo systemctl restart apache2"
          env:
            CLOUDSDK_CORE_DISABLE_PROMPTS: 1
            GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
