name: BUild and Deploy to Google Compute Engine

on:
  push:
    branches: ["master", "#177-Deploy-backend-automatic"]

env:
  PROJECT_ID: ${{ secrets.GCE_PROJECT }}

jobs:
  ssh:
      runs-on: 'ubuntu-latest'
      permissions:
        contents: 'read'
        id-token: 'write'

      steps:
        - name: 'Checkout'
          uses: 'actions/checkout@v3'

        - id: 'auth'
          name: 'Authenticate to Google Cloud'
          uses: 'google-github-actions/auth@v2'
          with:
            credentials_json: '${{ secrets.GCE_SA_KEY }}'
        - name: Run Deployment Script
          run: |
            chmod +x ${{ github.workspace }}/script-deploy/script.sh
            ${{ github.workspace }}/script-deploy/script.sh

        - name: 'Show Output'
          run: |-
            echo '${{ steps.ssh.outputs.stdout }}'
            echo '${{ steps.compute-ssh.outputs.stderr }}'