name: Django Tests

on:
  push:
    branches: [ "master", "#239-imatges-secrets-al-github" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Message
        run: echo "Workflow is running."

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.6

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Google Cloud credentials
        run: echo "$GOOGLE_APPLICATION_CREDENTIALS" > cultucat-serviceAcc.json

      - name: Run Django Tests with Coverage
        env:
          GOOGLE_APPLICATION_CREDENTIALS: cultucat-serviceAcc.json
        run: |
          echo "Running Django tests with coverage..."
          coverage run manage.py test
          coverage report -m --fail-under=80
